apiVersion: apps/v1
kind: Deployment
metadata:
  name: simpleapp
  namespace: training
  labels:
    app: simpleapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simpleapp
  template:
    metadata:
      labels:
        app: simpleapp
    spec:
      containers:
      - name: simpleapp
        image: 3.126.69.18/test/simpleapp:1.0
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: simpleapp
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: "/"
            port: 5000
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: "/"
            port: 5000
            scheme: "HTTP"
          initialDelaySeconds: 0
          periodSeconds: 30
          successThreshold: 1
          timeoutSeconds: 10
